### PR TITLE
Sainsmart dds120

### PR DESCRIPTION
**Pull request by msiegert**
Added a check if the scope/model has the required code/command for setting the coupling before trying to send the command...
Also changed the build on MacOS to a bundle

### CODE REVIEW

**Comment by Ho-Ro** [comment]
Thx, it works and looks good! Will play around some time before I merge into `master`. 
I've updated the Hantek 6022 firmware and model accordingly, AC/DC can be implemented also there after HW mod -> doc tbd.

**Comment by Ho-Ro** [comment]
Hi Markus,
I see a regression, probably introduced by 3f6b16c. The [ci process at travis](https://travis-ci.org/OpenHantek/OpenHantek6022) doesn't produce a correct MacOS binary anymore, only this:
https://github.com/OpenHantek/OpenHantek6022/releases/download/v2.17-rc1/openhantek_20191020-8d3fa7c-1_osx_x86_64.tar.gz
Please have a look at https://github.com/OpenHantek/OpenHantek6022/blob/master/.travis.yml because I don't have any chance to check this MacOS build process.
Martin

**Comment by msiegert** [comment]
Hi Martin,

just cloned your rep again and it still builds fine on my mac. I think the problem is that the location of the actual mac binary has changed and travis doesn't find it. But I see no configuration option in .travis.vml for the location?! it used to be build/openhantek/OpenHantek, but now it is build/openhantek/OpenHantek.app/Contents/MacOS/OpenHantek. We could add a config option so that cmake normally builds a plain binary and only when the option is set builds the app bundle...

**Comment by msiegert** [comment]
please replace openHantek/CMakeLists.txt with the attached file. This will add an option "BUILD_MACOSX_BUNDLE" which is set to OFF as default. With this, "make package" will include the binary again.
[CMakeLists.txt](https://github.com/OpenHantek/OpenHantek6022/files/3748153/CMakeLists.txt)

**Pull request merged**
